/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SignupEmailRouteImport } from './routes/signup-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth'
import { Route as LayoutSplatRouteImport } from './routes/_layout/$'
import { Route as LayoutShareIdRouteImport } from './routes/_layout/share/$id'
import { Route as LayoutAuthSubscriptionRouteImport } from './routes/_layout/_auth/subscription'
import { Route as LayoutAuthSettingsRouteImport } from './routes/_layout/_auth/settings'
import { Route as LayoutAuthHistoryRouteImport } from './routes/_layout/_auth/history'
import { Route as LayoutAuthEditorIdRouteImport } from './routes/_layout/_auth/editor/$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmailRoute = SignupEmailRouteImport.update({
  id: '/signup-email',
  path: '/signup-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSplatRoute = LayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShareIdRoute = LayoutShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthSubscriptionRoute = LayoutAuthSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthSettingsRoute = LayoutAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthHistoryRoute = LayoutAuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthEditorIdRoute = LayoutAuthEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => LayoutAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/signup-email': typeof SignupEmailRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/update-password': typeof UpdatePasswordRoute
  '/$': typeof LayoutSplatRoute
  '/history': typeof LayoutAuthHistoryRoute
  '/settings': typeof LayoutAuthSettingsRoute
  '/subscription': typeof LayoutAuthSubscriptionRoute
  '/share/$id': typeof LayoutShareIdRoute
  '/editor/$id': typeof LayoutAuthEditorIdRoute
}
export interface FileRoutesByTo {
  '/confirm-email': typeof ConfirmEmailRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/signup-email': typeof SignupEmailRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/update-password': typeof UpdatePasswordRoute
  '/$': typeof LayoutSplatRoute
  '/': typeof LayoutIndexRoute
  '/history': typeof LayoutAuthHistoryRoute
  '/settings': typeof LayoutAuthSettingsRoute
  '/subscription': typeof LayoutAuthSubscriptionRoute
  '/share/$id': typeof LayoutShareIdRoute
  '/editor/$id': typeof LayoutAuthEditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/signup-email': typeof SignupEmailRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_layout/$': typeof LayoutSplatRoute
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_auth/history': typeof LayoutAuthHistoryRoute
  '/_layout/_auth/settings': typeof LayoutAuthSettingsRoute
  '/_layout/_auth/subscription': typeof LayoutAuthSubscriptionRoute
  '/_layout/share/$id': typeof LayoutShareIdRoute
  '/_layout/_auth/editor/$id': typeof LayoutAuthEditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/privacy-policy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/signup-email'
    | '/terms-of-service'
    | '/update-password'
    | '/$'
    | '/history'
    | '/settings'
    | '/subscription'
    | '/share/$id'
    | '/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confirm-email'
    | '/privacy-policy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/signup-email'
    | '/terms-of-service'
    | '/update-password'
    | '/$'
    | '/'
    | '/history'
    | '/settings'
    | '/subscription'
    | '/share/$id'
    | '/editor/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/confirm-email'
    | '/privacy-policy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/signup-email'
    | '/terms-of-service'
    | '/update-password'
    | '/_layout/$'
    | '/_layout/_auth'
    | '/_layout/'
    | '/_layout/_auth/history'
    | '/_layout/_auth/settings'
    | '/_layout/_auth/subscription'
    | '/_layout/share/$id'
    | '/_layout/_auth/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SignupEmailRoute: typeof SignupEmailRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-email': {
      id: '/signup-email'
      path: '/signup-email'
      fullPath: '/signup-email'
      preLoaderRoute: typeof SignupEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$': {
      id: '/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof LayoutSplatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/share/$id': {
      id: '/_layout/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof LayoutShareIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth/subscription': {
      id: '/_layout/_auth/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof LayoutAuthSubscriptionRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/settings': {
      id: '/_layout/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthSettingsRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/history': {
      id: '/_layout/_auth/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutAuthHistoryRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/editor/$id': {
      id: '/_layout/_auth/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof LayoutAuthEditorIdRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
  }
}

interface LayoutAuthRouteChildren {
  LayoutAuthHistoryRoute: typeof LayoutAuthHistoryRoute
  LayoutAuthSettingsRoute: typeof LayoutAuthSettingsRoute
  LayoutAuthSubscriptionRoute: typeof LayoutAuthSubscriptionRoute
  LayoutAuthEditorIdRoute: typeof LayoutAuthEditorIdRoute
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthHistoryRoute: LayoutAuthHistoryRoute,
  LayoutAuthSettingsRoute: LayoutAuthSettingsRoute,
  LayoutAuthSubscriptionRoute: LayoutAuthSubscriptionRoute,
  LayoutAuthEditorIdRoute: LayoutAuthEditorIdRoute,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutSplatRoute: typeof LayoutSplatRoute
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutShareIdRoute: typeof LayoutShareIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSplatRoute: LayoutSplatRoute,
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutShareIdRoute: LayoutShareIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SignupEmailRoute: SignupEmailRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
